version: '3.3'
services:
  mariadb:
    image: mariadb:5.5.58
    restart: always
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./docker/mariadb/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: lidsys
      MYSQL_USER: lidsys
      MYSQL_PASSWORD: lidsys
      MYSQL_DATABASE: dev_lidsys
