version: '3.7'
services:
  nginx:
    image: nginx:1.17.3-alpine
    restart: always
    volumes:
      - .:/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/app.conf
    networks:
      default:
      reverse-proxy:
        aliases:
          - pickem
          - pickem.frontend
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: always
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - .:/app
      - ~/.composer:/root/.composer
    working_dir: /app
    environment:
      - APP_ENV
      - DATABASE_URL
      - HONEYBADGER_API_KEY

  postgres:
    image: postgres:11.5-alpine
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - PSQL_HISTORY=/var/lib/postgresql/history/pickem
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/psql-history:/var/lib/postgresql/history

  postgres-snapshot:
    build:
      context: .
      dockerfile: docker/postgres-snapshot/Dockerfile
    restart: 'no'
    environment:
      - DATABASE_URL
      - DROPBOX_TOKEN
      - HONEYBADGER_POSTGRES_SNAPSHOTS_CHECKIN
    volumes:
      - ./bin:/app/bin

  scraper:
    build:
      context: .
      dockerfile: docker/scraper/Dockerfile
    restart: "always"
    volumes:
      - ./scraper/index.js:/app/index.js

networks:
  reverse-proxy:
    external:
      name: "${REVERSE_PROXY_NETWORK:-frontend}"
